# Generated by coldstorage's release workflow — edits to the version and
# checksums are overwritten on every release.
class Coldstorage < Formula
  desc "Live terminal dashboard for a fleet of git repositories"
  homepage "https://github.com/crueber/coldstorage"
  version "1.0.7"
  license "MIT"

  livecheck do
    url "https://github.com/crueber/coldstorage/releases/latest"
    regex(%r{href=["']?[^/"]*/releases/tag/v?(\d+\.\d+\.\d+)["']}i)
    strategy :page_match
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_arm64.tar.gz"
      sha256 "682ffc9622d1d9a43cfac3a6bb98d4aa528c7fe20b02544d44bdd68ddf9a50af"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_x86_64.tar.gz"
      sha256 "0fa2f738898eaa4e16f4b98866564cc750aab8c77788dd6f732cca7d072c090c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_arm64.tar.gz"
      sha256 "2f416027eed6f3e9678606c1311507d503eb57c0dc7f4e2d64302fdcf195ed45"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_x86_64.tar.gz"
      sha256 "b6ab18c263515efc316559dcafaab752626fd245d66defb6f61c9c9d08de31b3"
    end
  end

  def install
    bin.install "coldstorage"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coldstorage --version")
  end
end
