# Generated by coldstorage's release workflow — edits to the version and
# checksums are overwritten on every release.
class Coldstorage < Formula
  desc "Live terminal dashboard for a fleet of git repositories"
  homepage "https://github.com/crueber/coldstorage"
  version "1.0.11"
  license "MIT"

  livecheck do
    url "https://github.com/crueber/coldstorage/releases/latest"
    regex(%r{href=["']?[^/"]*/releases/tag/v?(\d+\.\d+\.\d+)["']}i)
    strategy :page_match
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_arm64.tar.gz"
      sha256 "5a31d98d8f2d57fc8ed5e5021e1bbd24780146504a55a7015b83dc04f3e23395"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_x86_64.tar.gz"
      sha256 "dd1027825f8a8209aa55f18b0232609f42c3833708c4ddf868c03b939ad4cb04"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_arm64.tar.gz"
      sha256 "96d4ae596270a0c4643b8fc870c8e47557bc7ad29563ddb174c79fbe9fd31696"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_x86_64.tar.gz"
      sha256 "dddfbe3b8115656715988e41a1c23cf3ce21c987a86ce5905a996cf7a978bf21"
    end
  end

  def install
    bin.install "coldstorage"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coldstorage --version")
  end
end
