# Generated by coldstorage's release workflow — edits to the version and
# checksums are overwritten on every release.
class Coldstorage < Formula
  desc "Live terminal dashboard for a fleet of git repositories"
  homepage "https://github.com/crueber/coldstorage"
  version "1.0.13"
  license "MIT"

  livecheck do
    url "https://github.com/crueber/coldstorage/releases/latest"
    regex(%r{href=["']?[^/"]*/releases/tag/v?(\d+\.\d+\.\d+)["']}i)
    strategy :page_match
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_arm64.tar.gz"
      sha256 "f57eac9fe420b8e8b322ac169fee95ca54542a5e89c85663ac27229427805659"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_x86_64.tar.gz"
      sha256 "82c35ab13d1598be1d4b4677f2b9861fed33e1083a36643910ca07148f648635"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_arm64.tar.gz"
      sha256 "624fcfe23426e6d497e87c0ed6b6b8bc2710d171052cd70f1775aa3d3e26b947"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_x86_64.tar.gz"
      sha256 "6833a5aafcea36e87dc697dced54926a30c33130c76e354e3def309fc7f3b4d6"
    end
  end

  def install
    bin.install "coldstorage"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coldstorage --version")
  end
end
